plugins:
  - jekyll-relative-links
  - jekyll-menus
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - ABOUT.md

theme: jekyll-theme-cayman

show_downloads: true

sidebar:
  title: "Sample Title"
  nav: sidebar-sample
  
