plugins:
  - jekyll-relative-links
  - jekyll-menus
relative_links:
  enabled: true
  collections: true
output_dir: "."
navbar:
  title: "Quick Menu"
  left:
    - text: "Home"
      href: README.html
    - text: "Syntax"
      href: syntax.html
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - ABOUT.md

theme: jekyll-theme-cayman


